version: '3.8'


services:
  web:
    build: ./weatherbotapi
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./weatherbotapi/:/usr/src/weather-bot-proj/weatherbotapi
    ports:
      - 8000:8000
    env_file:
      - ./botenv.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuser
      - POSTGRES_DB=weatherbotapi
volumes:
  postgres_data: