# Generated by Django 3.2.3 on 2021-05-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_clientrequest_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
