# Generated by Django 3.2.3 on 2021-05-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210528_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='weather',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.weather'),
        ),
    ]
