# Generated by Django 3.2.3 on 2021-05-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_clientrequest_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
